import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Description from "./components/Description";
import Portfolio from "./components/Portfolio";
import Timeline from "./components/Timeline";
import ContactForm from "./components/ContactForm";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="w-full pt-20 px-10 flex flex-col gap-16 items-center min-h-screen bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-gray-200 via-gray-400 to-gray-600">
          <Description />
          <Portfolio />
          <Timeline />
          <ContactForm />
          <Footer />
        </div>
      </main>
    </>
  );
}
